/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChartVistCreateNestedManyWithoutStafsInput } from "./ChartVistCreateNestedManyWithoutStafsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { SchoolCreateNestedManyWithoutStafsInput } from "./SchoolCreateNestedManyWithoutStafsInput";
import { SchoolDistrictWhereUniqueInput } from "../../schoolDistrict/base/SchoolDistrictWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class StafCreateInput {
  @ApiProperty({
    required: false,
    type: () => ChartVistCreateNestedManyWithoutStafsInput,
  })
  @ValidateNested()
  @Type(() => ChartVistCreateNestedManyWithoutStafsInput)
  @IsOptional()
  @Field(() => ChartVistCreateNestedManyWithoutStafsInput, {
    nullable: true,
  })
  chartVists?: ChartVistCreateNestedManyWithoutStafsInput;

  @ApiProperty({
    required: false,
    type: () => SchoolCreateNestedManyWithoutStafsInput,
  })
  @ValidateNested()
  @Type(() => SchoolCreateNestedManyWithoutStafsInput)
  @IsOptional()
  @Field(() => SchoolCreateNestedManyWithoutStafsInput, {
    nullable: true,
  })
  school?: SchoolCreateNestedManyWithoutStafsInput;

  @ApiProperty({
    required: false,
    type: () => SchoolDistrictWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolDistrictWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolDistrictWhereUniqueInput, {
    nullable: true,
  })
  schoolDistricts?: SchoolDistrictWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  user!: UserWhereUniqueInput;
}

export { StafCreateInput };
