/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StafService } from "../staf.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StafCreateInput } from "./StafCreateInput";
import { StafWhereInput } from "./StafWhereInput";
import { StafWhereUniqueInput } from "./StafWhereUniqueInput";
import { StafFindManyArgs } from "./StafFindManyArgs";
import { StafUpdateInput } from "./StafUpdateInput";
import { Staf } from "./Staf";
import { ChartVistFindManyArgs } from "../../chartVist/base/ChartVistFindManyArgs";
import { ChartVist } from "../../chartVist/base/ChartVist";
import { ChartVistWhereUniqueInput } from "../../chartVist/base/ChartVistWhereUniqueInput";
import { SchoolFindManyArgs } from "../../school/base/SchoolFindManyArgs";
import { School } from "../../school/base/School";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StafControllerBase {
  constructor(
    protected readonly service: StafService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Staf })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: StafCreateInput): Promise<Staf> {
    return await this.service.create({
      data: {
        ...data,

        schoolDistricts: data.schoolDistricts
          ? {
              connect: data.schoolDistricts,
            }
          : undefined,

        user: {
          connect: data.user,
        },
      },
      select: {
        createdAt: true,
        id: true,

        schoolDistricts: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Staf] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(StafFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Staf[]> {
    const args = plainToClass(StafFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        schoolDistricts: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Staf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: StafWhereUniqueInput
  ): Promise<Staf | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        schoolDistricts: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Staf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() data: StafUpdateInput
  ): Promise<Staf | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          schoolDistricts: data.schoolDistricts
            ? {
                connect: data.schoolDistricts,
              }
            : undefined,

          user: {
            connect: data.user,
          },
        },
        select: {
          createdAt: true,
          id: true,

          schoolDistricts: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Staf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: StafWhereUniqueInput
  ): Promise<Staf | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          schoolDistricts: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ChartVist",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/chartVists")
  @ApiNestedQuery(ChartVistFindManyArgs)
  async findManyChartVists(
    @common.Req() request: Request,
    @common.Param() params: StafWhereUniqueInput
  ): Promise<ChartVist[]> {
    const query = plainToClass(ChartVistFindManyArgs, request.query);
    const results = await this.service.findChartVists(params.id, {
      ...query,
      select: {
        chartType: true,
        createdAt: true,
        endTime: true,
        id: true,

        school: {
          select: {
            id: true,
          },
        },

        staf: {
          select: {
            id: true,
          },
        },

        startTime: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/chartVists")
  async connectChartVists(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() body: ChartVistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chartVists: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/chartVists")
  async updateChartVists(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() body: ChartVistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chartVists: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/chartVists")
  async disconnectChartVists(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() body: ChartVistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chartVists: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/school")
  @ApiNestedQuery(SchoolFindManyArgs)
  async findManySchool(
    @common.Req() request: Request,
    @common.Param() params: StafWhereUniqueInput
  ): Promise<School[]> {
    const query = plainToClass(SchoolFindManyArgs, request.query);
    const results = await this.service.findSchool(params.id, {
      ...query,
      select: {
        activeSuscription: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        parent: {
          select: {
            id: true,
          },
        },

        schoolDistrict: {
          select: {
            id: true,
          },
        },

        state: true,
        township: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/school")
  async connectSchool(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() body: SchoolWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      school: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/school")
  async updateSchool(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() body: SchoolWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      school: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/school")
  async disconnectSchool(
    @common.Param() params: StafWhereUniqueInput,
    @common.Body() body: SchoolWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      school: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
