/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumChartVistChartType } from "./EnumChartVistChartType";
import {
  IsEnum,
  IsString,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { Type } from "class-transformer";
import { StafWhereUniqueInput } from "../../staf/base/StafWhereUniqueInput";
import { StudentWhereUniqueInput } from "../../student/base/StudentWhereUniqueInput";
import { TreatmentCreateNestedManyWithoutChartVistsInput } from "./TreatmentCreateNestedManyWithoutChartVistsInput";

@InputType()
class ChartVistCreateInput {
  @ApiProperty({
    required: true,
    enum: EnumChartVistChartType,
  })
  @IsEnum(EnumChartVistChartType)
  @Field(() => EnumChartVistChartType)
  chartType!: "Type_1" | "Type_2";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  endTime?: string | null;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => StafWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StafWhereUniqueInput)
  @IsOptional()
  @Field(() => StafWhereUniqueInput, {
    nullable: true,
  })
  staf?: StafWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => StudentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StudentWhereUniqueInput)
  @IsOptional()
  @Field(() => StudentWhereUniqueInput, {
    nullable: true,
  })
  student?: StudentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TreatmentCreateNestedManyWithoutChartVistsInput,
  })
  @ValidateNested()
  @Type(() => TreatmentCreateNestedManyWithoutChartVistsInput)
  @IsOptional()
  @Field(() => TreatmentCreateNestedManyWithoutChartVistsInput, {
    nullable: true,
  })
  treatments?: TreatmentCreateNestedManyWithoutChartVistsInput;
}

export { ChartVistCreateInput };
