/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, ValidateNested, IsOptional } from "class-validator";
import { RoleCreateNestedManyWithoutSchoolDistrictsInput } from "./RoleCreateNestedManyWithoutSchoolDistrictsInput";
import { Type } from "class-transformer";
import { SchoolCreateNestedManyWithoutSchoolDistrictsInput } from "./SchoolCreateNestedManyWithoutSchoolDistrictsInput";
import { StafCreateNestedManyWithoutSchoolDistrictsInput } from "./StafCreateNestedManyWithoutSchoolDistrictsInput";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";

@InputType()
class SchoolDistrictCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => RoleCreateNestedManyWithoutSchoolDistrictsInput,
  })
  @ValidateNested()
  @Type(() => RoleCreateNestedManyWithoutSchoolDistrictsInput)
  @IsOptional()
  @Field(() => RoleCreateNestedManyWithoutSchoolDistrictsInput, {
    nullable: true,
  })
  roles?: RoleCreateNestedManyWithoutSchoolDistrictsInput;

  @ApiProperty({
    required: false,
    type: () => SchoolCreateNestedManyWithoutSchoolDistrictsInput,
  })
  @ValidateNested()
  @Type(() => SchoolCreateNestedManyWithoutSchoolDistrictsInput)
  @IsOptional()
  @Field(() => SchoolCreateNestedManyWithoutSchoolDistrictsInput, {
    nullable: true,
  })
  schools?: SchoolCreateNestedManyWithoutSchoolDistrictsInput;

  @ApiProperty({
    required: false,
    type: () => StafCreateNestedManyWithoutSchoolDistrictsInput,
  })
  @ValidateNested()
  @Type(() => StafCreateNestedManyWithoutSchoolDistrictsInput)
  @IsOptional()
  @Field(() => StafCreateNestedManyWithoutSchoolDistrictsInput, {
    nullable: true,
  })
  stafs?: StafCreateNestedManyWithoutSchoolDistrictsInput;

  @ApiProperty({
    required: false,
    type: () => SubscriptionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionWhereUniqueInput)
  @IsOptional()
  @Field(() => SubscriptionWhereUniqueInput, {
    nullable: true,
  })
  subscription?: SubscriptionWhereUniqueInput | null;
}

export { SchoolDistrictCreateInput };
