/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MedicalRecordService } from "../medicalRecord.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MedicalRecordCreateInput } from "./MedicalRecordCreateInput";
import { MedicalRecordWhereInput } from "./MedicalRecordWhereInput";
import { MedicalRecordWhereUniqueInput } from "./MedicalRecordWhereUniqueInput";
import { MedicalRecordFindManyArgs } from "./MedicalRecordFindManyArgs";
import { MedicalRecordUpdateInput } from "./MedicalRecordUpdateInput";
import { MedicalRecord } from "./MedicalRecord";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MedicalRecordControllerBase {
  constructor(
    protected readonly service: MedicalRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MedicalRecord })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: MedicalRecordCreateInput
  ): Promise<MedicalRecord> {
    return await this.service.create({
      data: {
        ...data,

        approval: data.approval
          ? {
              connect: data.approval,
            }
          : undefined,

        chartVist: data.chartVist
          ? {
              connect: data.chartVist,
            }
          : undefined,

        student: data.student
          ? {
              connect: data.student,
            }
          : undefined,
      },
      select: {
        approval: {
          select: {
            id: true,
          },
        },

        category: true,

        chartVist: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        generalDetails: true,
        id: true,
        medicationDetails: true,

        student: {
          select: {
            id: true,
          },
        },

        timingDetails: true,
        treatmentDetails: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [MedicalRecord] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(MedicalRecordFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<MedicalRecord[]> {
    const args = plainToClass(MedicalRecordFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        approval: {
          select: {
            id: true,
          },
        },

        category: true,

        chartVist: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        generalDetails: true,
        id: true,
        medicationDetails: true,

        student: {
          select: {
            id: true,
          },
        },

        timingDetails: true,
        treatmentDetails: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MedicalRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: MedicalRecordWhereUniqueInput
  ): Promise<MedicalRecord | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        approval: {
          select: {
            id: true,
          },
        },

        category: true,

        chartVist: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        generalDetails: true,
        id: true,
        medicationDetails: true,

        student: {
          select: {
            id: true,
          },
        },

        timingDetails: true,
        treatmentDetails: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MedicalRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: MedicalRecordWhereUniqueInput,
    @common.Body() data: MedicalRecordUpdateInput
  ): Promise<MedicalRecord | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          approval: data.approval
            ? {
                connect: data.approval,
              }
            : undefined,

          chartVist: data.chartVist
            ? {
                connect: data.chartVist,
              }
            : undefined,

          student: data.student
            ? {
                connect: data.student,
              }
            : undefined,
        },
        select: {
          approval: {
            select: {
              id: true,
            },
          },

          category: true,

          chartVist: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          generalDetails: true,
          id: true,
          medicationDetails: true,

          student: {
            select: {
              id: true,
            },
          },

          timingDetails: true,
          treatmentDetails: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MedicalRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: MedicalRecordWhereUniqueInput
  ): Promise<MedicalRecord | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          approval: {
            select: {
              id: true,
            },
          },

          category: true,

          chartVist: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          generalDetails: true,
          id: true,
          medicationDetails: true,

          student: {
            select: {
              id: true,
            },
          },

          timingDetails: true,
          treatmentDetails: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
