/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsEnum,
  IsJSON,
  ValidateNested,
} from "class-validator";
import { EnumUserLanguage } from "./EnumUserLanguage";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { StafUpdateManyWithoutUsersInput } from "./StafUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserLanguage,
  })
  @IsEnum(EnumUserLanguage)
  @IsOptional()
  @Field(() => EnumUserLanguage, {
    nullable: true,
  })
  language?: "English" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  profilePicUrl?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => StafUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StafUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StafUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  stafs?: StafUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput };
