/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ApprovalService } from "../approval.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApprovalCreateInput } from "./ApprovalCreateInput";
import { ApprovalWhereInput } from "./ApprovalWhereInput";
import { ApprovalWhereUniqueInput } from "./ApprovalWhereUniqueInput";
import { ApprovalFindManyArgs } from "./ApprovalFindManyArgs";
import { ApprovalUpdateInput } from "./ApprovalUpdateInput";
import { Approval } from "./Approval";
import { ParentFindManyArgs } from "../../parent/base/ParentFindManyArgs";
import { Parent } from "../../parent/base/Parent";
import { ParentWhereUniqueInput } from "../../parent/base/ParentWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApprovalControllerBase {
  constructor(
    protected readonly service: ApprovalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Approval })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ApprovalCreateInput): Promise<Approval> {
    return await this.service.create({
      data: {
        ...data,

        record: {
          connect: data.record,
        },

        student: data.student
          ? {
              connect: data.student,
            }
          : undefined,
      },
      select: {
        authorisationLetter: true,
        createdAt: true,
        description: true,
        id: true,

        record: {
          select: {
            id: true,
          },
        },

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Approval] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ApprovalFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Approval[]> {
    const args = plainToClass(ApprovalFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        authorisationLetter: true,
        createdAt: true,
        description: true,
        id: true,

        record: {
          select: {
            id: true,
          },
        },

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Approval })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ApprovalWhereUniqueInput
  ): Promise<Approval | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        authorisationLetter: true,
        createdAt: true,
        description: true,
        id: true,

        record: {
          select: {
            id: true,
          },
        },

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Approval })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ApprovalWhereUniqueInput,
    @common.Body() data: ApprovalUpdateInput
  ): Promise<Approval | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          record: {
            connect: data.record,
          },

          student: data.student
            ? {
                connect: data.student,
              }
            : undefined,
        },
        select: {
          authorisationLetter: true,
          createdAt: true,
          description: true,
          id: true,

          record: {
            select: {
              id: true,
            },
          },

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Approval })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ApprovalWhereUniqueInput
  ): Promise<Approval | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          authorisationLetter: true,
          createdAt: true,
          description: true,
          id: true,

          record: {
            select: {
              id: true,
            },
          },

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/approvedBy")
  @ApiNestedQuery(ParentFindManyArgs)
  async findManyApprovedBy(
    @common.Req() request: Request,
    @common.Param() params: ApprovalWhereUniqueInput
  ): Promise<Parent[]> {
    const query = plainToClass(ParentFindManyArgs, request.query);
    const results = await this.service.findApprovedBy(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/approvedBy")
  async connectApprovedBy(
    @common.Param() params: ApprovalWhereUniqueInput,
    @common.Body() body: ParentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvedBy: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/approvedBy")
  async updateApprovedBy(
    @common.Param() params: ApprovalWhereUniqueInput,
    @common.Body() body: ParentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvedBy: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/approvedBy")
  async disconnectApprovedBy(
    @common.Param() params: ApprovalWhereUniqueInput,
    @common.Body() body: ParentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvedBy: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
