/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApprovalUpdateManyWithoutParentsInput } from "./ApprovalUpdateManyWithoutParentsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { SchoolUpdateManyWithoutParentsInput } from "./SchoolUpdateManyWithoutParentsInput";
import { StudentUpdateManyWithoutParentsInput } from "./StudentUpdateManyWithoutParentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ParentUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ApprovalUpdateManyWithoutParentsInput,
  })
  @ValidateNested()
  @Type(() => ApprovalUpdateManyWithoutParentsInput)
  @IsOptional()
  @Field(() => ApprovalUpdateManyWithoutParentsInput, {
    nullable: true,
  })
  approvals?: ApprovalUpdateManyWithoutParentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => SchoolUpdateManyWithoutParentsInput,
  })
  @ValidateNested()
  @Type(() => SchoolUpdateManyWithoutParentsInput)
  @IsOptional()
  @Field(() => SchoolUpdateManyWithoutParentsInput, {
    nullable: true,
  })
  schools?: SchoolUpdateManyWithoutParentsInput;

  @ApiProperty({
    required: false,
    type: () => StudentUpdateManyWithoutParentsInput,
  })
  @ValidateNested()
  @Type(() => StudentUpdateManyWithoutParentsInput)
  @IsOptional()
  @Field(() => StudentUpdateManyWithoutParentsInput, {
    nullable: true,
  })
  students?: StudentUpdateManyWithoutParentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ParentUpdateInput };
