/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StudentService } from "../student.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StudentCreateInput } from "./StudentCreateInput";
import { StudentWhereInput } from "./StudentWhereInput";
import { StudentWhereUniqueInput } from "./StudentWhereUniqueInput";
import { StudentFindManyArgs } from "./StudentFindManyArgs";
import { StudentUpdateInput } from "./StudentUpdateInput";
import { Student } from "./Student";
import { ApprovalFindManyArgs } from "../../approval/base/ApprovalFindManyArgs";
import { Approval } from "../../approval/base/Approval";
import { ApprovalWhereUniqueInput } from "../../approval/base/ApprovalWhereUniqueInput";
import { ChartVistFindManyArgs } from "../../chartVist/base/ChartVistFindManyArgs";
import { ChartVist } from "../../chartVist/base/ChartVist";
import { ChartVistWhereUniqueInput } from "../../chartVist/base/ChartVistWhereUniqueInput";
import { ParentFindManyArgs } from "../../parent/base/ParentFindManyArgs";
import { Parent } from "../../parent/base/Parent";
import { ParentWhereUniqueInput } from "../../parent/base/ParentWhereUniqueInput";
import { TreatmentFindManyArgs } from "../../treatment/base/TreatmentFindManyArgs";
import { Treatment } from "../../treatment/base/Treatment";
import { TreatmentWhereUniqueInput } from "../../treatment/base/TreatmentWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StudentControllerBase {
  constructor(
    protected readonly service: StudentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Student })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: StudentCreateInput): Promise<Student> {
    return await this.service.create({
      data: {
        ...data,

        school: {
          connect: data.school,
        },

        user: {
          connect: data.user,
        },
      },
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        status: true,
        studentId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Student] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(StudentFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Student[]> {
    const args = plainToClass(StudentFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        status: true,
        studentId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Student })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Student | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        status: true,
        studentId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Student })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() data: StudentUpdateInput
  ): Promise<Student | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          school: {
            connect: data.school,
          },

          user: {
            connect: data.user,
          },
        },
        select: {
          address: true,
          createdAt: true,
          id: true,
          name: true,

          school: {
            select: {
              id: true,
            },
          },

          status: true,
          studentId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Student })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Student | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          name: true,

          school: {
            select: {
              id: true,
            },
          },

          status: true,
          studentId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/approvals")
  @ApiNestedQuery(ApprovalFindManyArgs)
  async findManyApprovals(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Approval[]> {
    const query = plainToClass(ApprovalFindManyArgs, request.query);
    const results = await this.service.findApprovals(params.id, {
      ...query,
      select: {
        authorisationLetter: true,
        createdAt: true,
        description: true,
        id: true,

        record: {
          select: {
            id: true,
          },
        },

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/approvals")
  async connectApprovals(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ApprovalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvals: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/approvals")
  async updateApprovals(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ApprovalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvals: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/approvals")
  async disconnectApprovals(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ApprovalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvals: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ChartVist",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/chartVists")
  @ApiNestedQuery(ChartVistFindManyArgs)
  async findManyChartVists(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<ChartVist[]> {
    const query = plainToClass(ChartVistFindManyArgs, request.query);
    const results = await this.service.findChartVists(params.id, {
      ...query,
      select: {
        chartType: true,
        createdAt: true,
        endTime: true,
        id: true,

        school: {
          select: {
            id: true,
          },
        },

        staf: {
          select: {
            id: true,
          },
        },

        startTime: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/chartVists")
  async connectChartVists(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ChartVistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chartVists: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/chartVists")
  async updateChartVists(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ChartVistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chartVists: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/chartVists")
  async disconnectChartVists(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ChartVistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chartVists: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/parent")
  @ApiNestedQuery(ParentFindManyArgs)
  async findManyParent(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Parent[]> {
    const query = plainToClass(ParentFindManyArgs, request.query);
    const results = await this.service.findParent(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/parent")
  async connectParent(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ParentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parent: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/parent")
  async updateParent(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ParentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parent: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/parent")
  async disconnectParent(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ParentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parent: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Treatment",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/records")
  @ApiNestedQuery(TreatmentFindManyArgs)
  async findManyRecords(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Treatment[]> {
    const query = plainToClass(TreatmentFindManyArgs, request.query);
    const results = await this.service.findRecords(params.id, {
      ...query,
      select: {
        approval: {
          select: {
            id: true,
          },
        },

        chartVist: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        generalDetails: true,
        id: true,
        medicationDetails: true,

        student: {
          select: {
            id: true,
          },
        },

        timingDetails: true,
        treatmentDetails: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/records")
  async connectRecords(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: TreatmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/records")
  async updateRecords(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: TreatmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/records")
  async disconnectRecords(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: TreatmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
