/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ParentCreateNestedManyWithoutStudentsInput } from "./ParentCreateNestedManyWithoutStudentsInput";
import { Type } from "class-transformer";
import { RecordCreateNestedManyWithoutStudentsInput } from "./RecordCreateNestedManyWithoutStudentsInput";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class StudentCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ParentCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => ParentCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => ParentCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  parent?: ParentCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => RecordCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => RecordCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => RecordCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  records?: RecordCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: true,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @Field(() => SchoolWhereUniqueInput)
  school!: SchoolWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  studentId?: string | null;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  user!: UserWhereUniqueInput;
}

export { StudentCreateInput };
