/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSchoolArgs } from "./CreateSchoolArgs";
import { UpdateSchoolArgs } from "./UpdateSchoolArgs";
import { DeleteSchoolArgs } from "./DeleteSchoolArgs";
import { SchoolFindManyArgs } from "./SchoolFindManyArgs";
import { SchoolFindUniqueArgs } from "./SchoolFindUniqueArgs";
import { School } from "./School";
import { ChartVistFindManyArgs } from "../../chartVist/base/ChartVistFindManyArgs";
import { ChartVist } from "../../chartVist/base/ChartVist";
import { RoleFindManyArgs } from "../../role/base/RoleFindManyArgs";
import { Role } from "../../role/base/Role";
import { StafFindManyArgs } from "../../staf/base/StafFindManyArgs";
import { Staf } from "../../staf/base/Staf";
import { StudentFindManyArgs } from "../../student/base/StudentFindManyArgs";
import { Student } from "../../student/base/Student";
import { Parent } from "../../parent/base/Parent";
import { SchoolDistrict } from "../../schoolDistrict/base/SchoolDistrict";
import { SchoolService } from "../school.service";

@graphql.Resolver(() => School)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SchoolResolverBase {
  constructor(
    protected readonly service: SchoolService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "read",
    possession: "any",
  })
  async _schoolsMeta(
    @graphql.Args() args: SchoolFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [School])
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "read",
    possession: "any",
  })
  async schools(@graphql.Args() args: SchoolFindManyArgs): Promise<School[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => School, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "read",
    possession: "own",
  })
  async school(
    @graphql.Args() args: SchoolFindUniqueArgs
  ): Promise<School | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => School)
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "create",
    possession: "any",
  })
  async createSchool(@graphql.Args() args: CreateSchoolArgs): Promise<School> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        parent: args.data.parent
          ? {
              connect: args.data.parent,
            }
          : undefined,

        schoolDistrict: args.data.schoolDistrict
          ? {
              connect: args.data.schoolDistrict,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => School)
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "update",
    possession: "any",
  })
  async updateSchool(
    @graphql.Args() args: UpdateSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          parent: args.data.parent
            ? {
                connect: args.data.parent,
              }
            : undefined,

          schoolDistrict: args.data.schoolDistrict
            ? {
                connect: args.data.schoolDistrict,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => School)
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "delete",
    possession: "any",
  })
  async deleteSchool(
    @graphql.Args() args: DeleteSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ChartVist])
  @nestAccessControl.UseRoles({
    resource: "ChartVist",
    action: "read",
    possession: "any",
  })
  async chartVists(
    @graphql.Parent() parent: School,
    @graphql.Args() args: ChartVistFindManyArgs
  ): Promise<ChartVist[]> {
    const results = await this.service.findChartVists(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Role])
  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "read",
    possession: "any",
  })
  async roles(
    @graphql.Parent() parent: School,
    @graphql.Args() args: RoleFindManyArgs
  ): Promise<Role[]> {
    const results = await this.service.findRoles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Staf])
  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "read",
    possession: "any",
  })
  async stafs(
    @graphql.Parent() parent: School,
    @graphql.Args() args: StafFindManyArgs
  ): Promise<Staf[]> {
    const results = await this.service.findStafs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Student])
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "any",
  })
  async students(
    @graphql.Parent() parent: School,
    @graphql.Args() args: StudentFindManyArgs
  ): Promise<Student[]> {
    const results = await this.service.findStudents(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Parent, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "read",
    possession: "any",
  })
  async parent(@graphql.Parent() parent: School): Promise<Parent | null> {
    const result = await this.service.getParent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SchoolDistrict, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SchoolDistrict",
    action: "read",
    possession: "any",
  })
  async schoolDistrict(
    @graphql.Parent() parent: School
  ): Promise<SchoolDistrict | null> {
    const result = await this.service.getSchoolDistrict(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
