/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, School, Role, Staf, Subscription } from "@prisma/client";

export class SchoolServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.SchoolFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SchoolFindManyArgs>
  ): Promise<number> {
    return this.prisma.school.count(args);
  }

  async findMany<T extends Prisma.SchoolFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SchoolFindManyArgs>
  ): Promise<School[]> {
    return this.prisma.school.findMany(args);
  }
  async findOne<T extends Prisma.SchoolFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SchoolFindUniqueArgs>
  ): Promise<School | null> {
    return this.prisma.school.findUnique(args);
  }
  async create<T extends Prisma.SchoolCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SchoolCreateArgs>
  ): Promise<School> {
    return this.prisma.school.create<T>(args);
  }
  async update<T extends Prisma.SchoolUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SchoolUpdateArgs>
  ): Promise<School> {
    return this.prisma.school.update<T>(args);
  }
  async delete<T extends Prisma.SchoolDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SchoolDeleteArgs>
  ): Promise<School> {
    return this.prisma.school.delete(args);
  }

  async findRoles(
    parentId: string,
    args: Prisma.RoleFindManyArgs
  ): Promise<Role[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .roles(args);
  }

  async findStafs(
    parentId: string,
    args: Prisma.StafFindManyArgs
  ): Promise<Staf[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .stafs(args);
  }

  async findSubscriptionHistory(
    parentId: string,
    args: Prisma.SubscriptionFindManyArgs
  ): Promise<Subscription[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .SubscriptionHistory(args);
  }

  async getActiveSuscription(parentId: string): Promise<Subscription | null> {
    return this.prisma.school
      .findUnique({
        where: { id: parentId },
      })
      .activeSuscription();
  }
}
