/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { RoleCreateNestedManyWithoutSchoolsInput } from "./RoleCreateNestedManyWithoutSchoolsInput";
import { EnumSchoolSchoolDistrict } from "./EnumSchoolSchoolDistrict";
import { StafCreateNestedManyWithoutSchoolsInput } from "./StafCreateNestedManyWithoutSchoolsInput";
import { EnumSchoolState } from "./EnumSchoolState";
import { SubscriptionCreateNestedManyWithoutSchoolsInput } from "./SubscriptionCreateNestedManyWithoutSchoolsInput";
import { EnumSchoolTownship } from "./EnumSchoolTownship";

@InputType()
class SchoolCreateInput {
  @ApiProperty({
    required: false,
    type: () => SubscriptionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionWhereUniqueInput)
  @IsOptional()
  @Field(() => SubscriptionWhereUniqueInput, {
    nullable: true,
  })
  activeSuscription?: SubscriptionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RoleCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => RoleCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => RoleCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  roles?: RoleCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    enum: EnumSchoolSchoolDistrict,
  })
  @IsEnum(EnumSchoolSchoolDistrict)
  @IsOptional()
  @Field(() => EnumSchoolSchoolDistrict, {
    nullable: true,
  })
  schoolDistrict?: "A" | null;

  @ApiProperty({
    required: false,
    type: () => StafCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => StafCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => StafCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  stafs?: StafCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: true,
    enum: EnumSchoolState,
  })
  @IsEnum(EnumSchoolState)
  @Field(() => EnumSchoolState)
  state!: "Sate_1" | "State_2";

  @ApiProperty({
    required: false,
    type: () => SubscriptionCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => SubscriptionCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  SubscriptionHistory?: SubscriptionCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: true,
    enum: EnumSchoolTownship,
  })
  @IsEnum(EnumSchoolTownship)
  @Field(() => EnumSchoolTownship)
  township!: "T1" | "T2";
}

export { SchoolCreateInput };
