/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoleService } from "../role.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RoleCreateInput } from "./RoleCreateInput";
import { RoleWhereInput } from "./RoleWhereInput";
import { RoleWhereUniqueInput } from "./RoleWhereUniqueInput";
import { RoleFindManyArgs } from "./RoleFindManyArgs";
import { RoleUpdateInput } from "./RoleUpdateInput";
import { Role } from "./Role";
import { PermissionFindManyArgs } from "../../permission/base/PermissionFindManyArgs";
import { Permission } from "../../permission/base/Permission";
import { PermissionWhereUniqueInput } from "../../permission/base/PermissionWhereUniqueInput";
import { SchoolDistrictFindManyArgs } from "../../schoolDistrict/base/SchoolDistrictFindManyArgs";
import { SchoolDistrict } from "../../schoolDistrict/base/SchoolDistrict";
import { SchoolDistrictWhereUniqueInput } from "../../schoolDistrict/base/SchoolDistrictWhereUniqueInput";
import { SchoolFindManyArgs } from "../../school/base/SchoolFindManyArgs";
import { School } from "../../school/base/School";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { StafFindManyArgs } from "../../staf/base/StafFindManyArgs";
import { Staf } from "../../staf/base/Staf";
import { StafWhereUniqueInput } from "../../staf/base/StafWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RoleControllerBase {
  constructor(
    protected readonly service: RoleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Role })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: RoleCreateInput): Promise<Role> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Role] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(RoleFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Role[]> {
    const args = plainToClass(RoleFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Role })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: RoleWhereUniqueInput
  ): Promise<Role | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Role })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() data: RoleUpdateInput
  ): Promise<Role | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Role })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: RoleWhereUniqueInput
  ): Promise<Role | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Permission",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/permissions")
  @ApiNestedQuery(PermissionFindManyArgs)
  async findManyPermissions(
    @common.Req() request: Request,
    @common.Param() params: RoleWhereUniqueInput
  ): Promise<Permission[]> {
    const query = plainToClass(PermissionFindManyArgs, request.query);
    const results = await this.service.findPermissions(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,

        role: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/permissions")
  async connectPermissions(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: PermissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      permissions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/permissions")
  async updatePermissions(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: PermissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      permissions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/permissions")
  async disconnectPermissions(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: PermissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      permissions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SchoolDistrict",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/schoolDistricts")
  @ApiNestedQuery(SchoolDistrictFindManyArgs)
  async findManySchoolDistricts(
    @common.Req() request: Request,
    @common.Param() params: RoleWhereUniqueInput
  ): Promise<SchoolDistrict[]> {
    const query = plainToClass(SchoolDistrictFindManyArgs, request.query);
    const results = await this.service.findSchoolDistricts(params.id, {
      ...query,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,

        subscription: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/schoolDistricts")
  async connectSchoolDistricts(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: SchoolDistrictWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schoolDistricts: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/schoolDistricts")
  async updateSchoolDistricts(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: SchoolDistrictWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schoolDistricts: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/schoolDistricts")
  async disconnectSchoolDistricts(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: SchoolDistrictWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schoolDistricts: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "School",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/schools")
  @ApiNestedQuery(SchoolFindManyArgs)
  async findManySchools(
    @common.Req() request: Request,
    @common.Param() params: RoleWhereUniqueInput
  ): Promise<School[]> {
    const query = plainToClass(SchoolFindManyArgs, request.query);
    const results = await this.service.findSchools(params.id, {
      ...query,
      select: {
        abbreviation: true,
        address: true,
        createdAt: true,
        id: true,
        logoUrl: true,
        name: true,

        parent: {
          select: {
            id: true,
          },
        },

        schoolCode: true,

        schoolDistrict: {
          select: {
            id: true,
          },
        },

        state: true,
        status: true,
        township: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/schools")
  async connectSchools(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: SchoolWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schools: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/schools")
  async updateSchools(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: SchoolWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schools: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/schools")
  async disconnectSchools(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: SchoolWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schools: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Staf",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/stafs")
  @ApiNestedQuery(StafFindManyArgs)
  async findManyStafs(
    @common.Req() request: Request,
    @common.Param() params: RoleWhereUniqueInput
  ): Promise<Staf[]> {
    const query = plainToClass(StafFindManyArgs, request.query);
    const results = await this.service.findStafs(params.id, {
      ...query,
      select: {
        address: true,
        contactDetails: true,
        createdAt: true,
        destignation: true,
        fullName: true,
        gender: true,
        id: true,
        idNumber: true,
        officialEmail: true,
        race: true,

        role: {
          select: {
            id: true,
          },
        },

        schoolDistricts: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/stafs")
  async connectStafs(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: StafWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stafs: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/stafs")
  async updateStafs(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: StafWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stafs: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/stafs")
  async disconnectStafs(
    @common.Param() params: RoleWhereUniqueInput,
    @common.Body() body: StafWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stafs: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
