/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateMedicalRecordArgs } from "./CreateMedicalRecordArgs";
import { UpdateMedicalRecordArgs } from "./UpdateMedicalRecordArgs";
import { DeleteMedicalRecordArgs } from "./DeleteMedicalRecordArgs";
import { MedicalRecordFindManyArgs } from "./MedicalRecordFindManyArgs";
import { MedicalRecordFindUniqueArgs } from "./MedicalRecordFindUniqueArgs";
import { MedicalRecord } from "./MedicalRecord";
import { Approval } from "../../approval/base/Approval";
import { ChartVist } from "../../chartVist/base/ChartVist";
import { Student } from "../../student/base/Student";
import { MedicalRecordService } from "../medicalRecord.service";

@graphql.Resolver(() => MedicalRecord)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MedicalRecordResolverBase {
  constructor(
    protected readonly service: MedicalRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "read",
    possession: "any",
  })
  async _medicalRecordsMeta(
    @graphql.Args() args: MedicalRecordFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MedicalRecord])
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "read",
    possession: "any",
  })
  async medicalRecords(
    @graphql.Args() args: MedicalRecordFindManyArgs
  ): Promise<MedicalRecord[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MedicalRecord, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "read",
    possession: "own",
  })
  async medicalRecord(
    @graphql.Args() args: MedicalRecordFindUniqueArgs
  ): Promise<MedicalRecord | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MedicalRecord)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "create",
    possession: "any",
  })
  async createMedicalRecord(
    @graphql.Args() args: CreateMedicalRecordArgs
  ): Promise<MedicalRecord> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        approval: args.data.approval
          ? {
              connect: args.data.approval,
            }
          : undefined,

        chartVist: args.data.chartVist
          ? {
              connect: args.data.chartVist,
            }
          : undefined,

        student: args.data.student
          ? {
              connect: args.data.student,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MedicalRecord)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "update",
    possession: "any",
  })
  async updateMedicalRecord(
    @graphql.Args() args: UpdateMedicalRecordArgs
  ): Promise<MedicalRecord | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          approval: args.data.approval
            ? {
                connect: args.data.approval,
              }
            : undefined,

          chartVist: args.data.chartVist
            ? {
                connect: args.data.chartVist,
              }
            : undefined,

          student: args.data.student
            ? {
                connect: args.data.student,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MedicalRecord)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecord",
    action: "delete",
    possession: "any",
  })
  async deleteMedicalRecord(
    @graphql.Args() args: DeleteMedicalRecordArgs
  ): Promise<MedicalRecord | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Approval, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "any",
  })
  async approval(
    @graphql.Parent() parent: MedicalRecord
  ): Promise<Approval | null> {
    const result = await this.service.getApproval(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => ChartVist, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ChartVist",
    action: "read",
    possession: "any",
  })
  async chartVist(
    @graphql.Parent() parent: MedicalRecord
  ): Promise<ChartVist | null> {
    const result = await this.service.getChartVist(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Student, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "any",
  })
  async student(
    @graphql.Parent() parent: MedicalRecord
  ): Promise<Student | null> {
    const result = await this.service.getStudent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
